# Generated by Django 4.0.4 on 2022-05-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=30)),
                ('game_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game_Platform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('release_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.game')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AddField(
            model_name='game_publisher',
            name='game_publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.publisher'),
        ),
        migrations.AddField(
            model_name='game_platform',
            name='platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.genre'),
        ),
    ]
