# Generated by Django 4.0.4 on 2022-05-24 00:47

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_platform_name_game_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='enc_em_ua',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='user_account_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
