# Generated by Django 3.2 on 2022-05-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_user_account_name_user_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='enc_em_ua',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='enc_pw_ua',
            field=models.CharField(max_length=25),
        ),
    ]
