# Generated by Django 3.2 on 2022-05-25 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_usermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AddField(
            model_name='user_account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
