# Generated by Django 3.2 on 2022-05-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_rename_enc_em_ua_user_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='enc_pw_ua',
        ),
        migrations.AlterField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
