# Generated by Django 3.2 on 2022-05-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20220525_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_account',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
